. indent and remove pid file when stoping .

diff --git a/services/init.d/pulse2-package-server b/services/init.d/pulse2-package-server
--- a/services/init.d/pulse2-package-server
+++ b/services/init.d/pulse2-package-server
@@ -24,76 +24,77 @@
 
 # Variables
 DESC="Pulse2 Package Server : pulse2-package-server"
-DAEMON="##SBINDIR##/pulse2-package-server"
+DAEMON="/usr/sbin/pulse2-package-server"
 PIDFILE="/var/run/pulse2-package-server.pid"
 
 # Function to start daemon
 start () {
-	echo -n "Starting ${DESC} : "
-	# Start daemon (no need to demonize it)
-	# Do not start it if a pidfile already exist
-        if [ ! -e ${PIDFILE} ]
-	  then
-  	    ${DAEMON} >/dev/null 2>&1
-  	    # Get return code
-	    RETVAL=$?
-	  else
-	    RETVAL=1
-	fi
-	# If return code is 0, everything went fine
-	if [ ${RETVAL} -eq 0 ]
-	  then
-	    echo "done."
-	  else
-	    echo "failed."
-	fi
-	return ${RETVAL}
+    echo -n "Starting ${DESC} : "
+    # Start daemon (no need to demonize it)
+    # Do not start it if a pidfile already exist
+    if [ ! -e ${PIDFILE} ]
+    then
+        ${DAEMON} >/dev/null 2>&1
+        # Get return code
+        RETVAL=$?
+    else
+        RETVAL=1
+    fi
+    # If return code is 0, everything went fine
+    if [ ${RETVAL} -eq 0 ]
+    then
+        echo "done."
+    else
+        echo "failed."
+    fi
+    return ${RETVAL}
 }
 
 # Function to stop daemon
 stop () {
-	echo -n $"Stopping ${DESC} : "
-	# Check if the pidfile exists
-	if [ -e ${PIDFILE} ]
-	  then
-	    # If there's one, get the pid and send SIG 15
-	    kill -15 `cat ${PIDFILE}`
-	    # Get return code
-	    RETVAL=$?
-	  # If there's not pidfile, skipp kill and define RETVAL as 1
-	  else
-	  RETVAL=1
-	fi	
-	if [ ${RETVAL} -eq 0 ]
-	  then
-	    echo "done."
-	  else
-	    echo "failed."
-	fi
-	return ${RETVAL}
+    echo -n $"Stopping ${DESC} : "
+    # Check if the pidfile exists
+    if [ -e ${PIDFILE} ]
+    then
+        # If there's one, get the pid and send SIG 15
+        kill -15 `cat ${PIDFILE}`
+        # Get return code
+        RETVAL=$?
+        rm -f $PIDFILE
+        # If there's not pidfile, skipp kill and define RETVAL as 1
+    else
+        RETVAL=1
+    fi    
+    if [ ${RETVAL} -eq 0 ]
+    then
+        echo "done."
+    else
+        echo "failed."
+    fi
+    return ${RETVAL}
 }
 
 # Function to restart (run stop, then start)
 restart() {
-	stop
-	sleep 2
-	start
+    stop
+    sleep 2
+    start
 }
 
 case $1 in
-	start)
-		start
-	;;
-	stop)
-		stop
-	;;
-	restart | force-reload)
-		restart
-	;;
-	*)
+    start)
+        start
+    ;;
+    stop)
+        stop
+    ;;
+    restart | force-reload)
+        restart
+    ;;
+    *)
 
-	echo "Usage: ${0} {start|stop|restart|force-reload}"
-	exit 1
+    echo "Usage: ${0} {start|stop|restart|force-reload}"
+    exit 1
 esac
 
 exit ${RETVAL}
