pulse2-synch-masters: report errors

diff --git a/services/bin/pulse2-synch-masters b/services/bin/pulse2-synch-masters
--- a/services/bin/pulse2-synch-masters
+++ b/services/bin/pulse2-synch-masters
@@ -84,12 +84,28 @@ function synch_master_files() {
 	# Synchronize the contents
 	if [[ ${FROM_ENTITY_ID}  != "1" ]]; then
 		# We are synching from remote imaging server to pulse main server
-		local IP_IMAGING_SERVER=`echo "SELECT url FROM ImagingServer where fk_entity='${FROM_ENTITY_ID}' LIMIT 1;" | mysql --defaults-extra-file=/root/.my.cnf -uroot imaging --silent | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
+		IP_IMAGING_SERVER=`echo "SELECT url FROM ImagingServer where fk_entity='${FROM_ENTITY_ID}' LIMIT 1;" | mysql --defaults-extra-file=/root/.my.cnf -uroot imaging --silent | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
+		if [ ! $? -eq 0 ]; then
+			echo " 0 101% 0.00kB/s  0:00:00 mysql connection error" > /tmp/synch_masters_${PID}.log
+			exit 1
+		fi
 		rsync -az --info=progress2 root@${IP_IMAGING_SERVER}:/var/lib/pulse2/imaging/masters/${MASTER_UUID}/ /var/lib/pulse2/imaging/masters/${MASTER_UUID}/ >> /tmp/synch_masters_${PID}.log
+		if [ ! $? -eq 0 ]; then
+			echo " 0 101% 0.00kB/s  0:00:00 rsync error" > /tmp/synch_masters_${PID}.log
+			exit 1
+		fi
 	else
 		# We are synching from pulse main server to remote imaging server
-		local IP_IMAGING_SERVER=`echo "SELECT url FROM ImagingServer where fk_entity='${TO_ENTITY_ID}' LIMIT 1;" | mysql --defaults-extra-file=/root/.my.cnf -uroot imaging --silent | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
+		IP_IMAGING_SERVER=`echo "SELECT url FROM ImagingServer where fk_entity='${TO_ENTITY_ID}' LIMIT 1;" | mysql --defaults-extra-file=/root/.my.cnf -uroot imaging --silent | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
+		if [ ! $? -eq 0 ]; then
+			echo " 0 101% 0.00kB/s  0:00:00 mysql connection error" > /tmp/synch_masters_${PID}.log
+			exit 1
+		fi
 		rsync -az --info=progress2 /var/lib/pulse2/imaging/masters/${MASTER_UUID}/ root@${IP_IMAGING_SERVER}:/var/lib/pulse2/imaging/masters/${MASTER_UUID}/ >> /tmp/synch_masters_${PID}.log
+		if [ ! $? -eq 0 ]; then
+			echo " 0 101% 0.00kB/s  0:00:00 rsync error" > /tmp/synch_masters_${PID}.log
+			exit 1
+		fi
 	fi
 	
 	echo "### Synching contents of master ${MASTER_UUID}... Done"
